spring:
  application:
    name: var
    
server:
  port: 7001
  context-path: /var
  
var:
  platform:
    static:
      rootPath: /Users/Machintosh1983/Documents/workspace-brand-new/git/var-view/web
    research:
      webdriver:
        pool:
          maxIdle: 10
          maxTotal: 20
          testOnBorrow: false
          testOnReturn: false
          minIdle: 5
          lifo: false
          iniNum: 3
        driverpath: /usr/local/python/webdriver/chromedriver
        port: 48295
        
        